

/*product 1*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(001, 1, 'ADIDAS ESSENTIAL TEE', 45, 'top', 'black', 'small', 30, 'Sportswear staples are fundamental to streetwear, and nobody does them like adidas. This black tee is cut from comfortable cotton jersey and branded, simply but classically, with the brand’s famous white Trefoil embroidery.', 'res/product/product1-1.jpg', 'res/product/product1-2.jpg', 'res/product/product1-3.jpg', 'res/product/product1-4.jpg'),
(002, 1, 'ADIDAS ESSENTIAL TEE', 45, 'top', 'black', 'medium', 30, 'Sportswear staples are fundamental to streetwear, and nobody does them like adidas. This black tee is cut from comfortable cotton jersey and branded, simply but classically, with the brand’s famous white Trefoil embroidery.', 'res/product/product1-1.jpg', 'res/product/product1-2.jpg', 'res/product/product1-3.jpg', 'res/product/product1-4.jpg'),
(003, 1, 'ADIDAS ESSENTIAL TEE', 45, 'top', 'black', 'large', 30, 'Sportswear staples are fundamental to streetwear, and nobody does them like adidas. This black tee is cut from comfortable cotton jersey and branded, simply but classically, with the brand’s famous white Trefoil embroidery.', 'res/product/product1-1.jpg', 'res/product/product1-2.jpg', 'res/product/product1-3.jpg', 'res/product/product1-4.jpg'),
(004, 1, 'ADIDAS ESSENTIAL TEE', 45, 'top', 'white', 'small', 30, 'Sportswear staples are fundamental to streetwear, and nobody does them like adidas. This black tee is cut from comfortable cotton jersey and branded, simply but classically, with the brand’s famous white Trefoil embroidery.', 'res/product/product1-1.jpg', 'res/product/product1-2.jpg', 'res/product/product1-3.jpg', 'res/product/product1-4.jpg'),
(005, 1, 'ADIDAS ESSENTIAL TEE', 45, 'top', 'white', 'medium', 30, 'Sportswear staples are fundamental to streetwear, and nobody does them like adidas. This black tee is cut from comfortable cotton jersey and branded, simply but classically, with the brand’s famous white Trefoil embroidery.', 'res/product/product1-1.jpg', 'res/product/product1-2.jpg', 'res/product/product1-3.jpg', 'res/product/product1-4.jpg'),
(006, 1, 'ADIDAS ESSENTIAL TEE', 45, 'top', 'white', 'large', 30, 'Sportswear staples are fundamental to streetwear, and nobody does them like adidas. This black tee is cut from comfortable cotton jersey and branded, simply but classically, with the brand’s famous white Trefoil embroidery.', 'res/product/product1-1.jpg', 'res/product/product1-2.jpg', 'res/product/product1-3.jpg', 'res/product/product1-4.jpg');

/*product 2*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(007, 2, 'ADIDAS FRIENDS OF NATURE TEE', 45, 'top', 'black', 'small', 30, 'Join adidas’ Nature club with this sustainably focused t-shirt. Made from soft organic cotton, it’s undyed giving it a natural beige colour and features a vibrant, multicolour flower print which celebrates the great', 'res/product/product2-1.jpg', 'res/product/product2-2.jpg', 'res/product/product2-3.jpg', 'res/product/product2-4.jpg'),
(008, 2, 'ADIDAS FRIENDS OF NATURE TEE', 45, 'top', 'black', 'medium', 30, 'Join adidas’ Nature club with this sustainably focused t-shirt. Made from soft organic cotton, it’s undyed giving it a natural beige colour and features a vibrant, multicolour flower print which celebrates the great', 'res/product/product2-1.jpg', 'res/product/product2-2.jpg', 'res/product/product2-3.jpg', 'res/product/product2-4.jpg'),
(009, 2, 'ADIDAS FRIENDS OF NATURE TEE', 45, 'top', 'black', 'large', 30, 'Join adidas’ Nature club with this sustainably focused t-shirt. Made from soft organic cotton, it’s undyed giving it a natural beige colour and features a vibrant, multicolour flower print which celebrates the great', 'res/product/product2-1.jpg', 'res/product/product2-2.jpg', 'res/product/product2-3.jpg', 'res/product/product2-4.jpg'),
(010, 2, 'ADIDAS FRIENDS OF NATURE TEE', 45, 'top', 'white', 'small', 30, 'Join adidas’ Nature club with this sustainably focused t-shirt. Made from soft organic cotton, it’s undyed giving it a natural beige colour and features a vibrant, multicolour flower print which celebrates the great', 'res/product/product2-1.jpg', 'res/product/product2-2.jpg', 'res/product/product2-3.jpg', 'res/product/product2-4.jpg'),
(011, 2, 'ADIDAS FRIENDS OF NATURE TEE', 45, 'top', 'white', 'medium', 30, 'Join adidas’ Nature club with this sustainably focused t-shirt. Made from soft organic cotton, it’s undyed giving it a natural beige colour and features a vibrant, multicolour flower print which celebrates the great', 'res/product/product2-1.jpg', 'res/product/product2-2.jpg', 'res/product/product2-3.jpg', 'res/product/product2-4.jpg'),
(012, 2, 'ADIDAS FRIENDS OF NATURE TEE', 45, 'top', 'white', 'large', 30, 'Join adidas’ Nature club with this sustainably focused t-shirt. Made from soft organic cotton, it’s undyed giving it a natural beige colour and features a vibrant, multicolour flower print which celebrates the great', 'res/product/product2-1.jpg', 'res/product/product2-2.jpg', 'res/product/product2-3.jpg', 'res/product/product2-4.jpg');

/*product 3*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(013, 3, 'ADIDAS BECKENBAUER TRACK PANT', 95, 'bottom', 'black', 'small', 30, 'Paying homage to the former German footballer, this pair of track pants from adidas comes from the ‘Beckenbauer’ line-up. They’re styled in black with the signature stripes running along the seams, while the iconic Trefoil is embroidered at the thigh.', 'res/product/product3-1.jpg', 'res/product/product3-2.jpg', 'res/product/product3-3.jpg', 'res/product/product3-4.jpg'),
(014, 3, 'ADIDAS BECKENBAUER TRACK PANT', 95, 'bottom', 'black', 'medium', 30, 'Paying homage to the former German footballer, this pair of track pants from adidas comes from the ‘Beckenbauer’ line-up. They’re styled in black with the signature stripes running along the seams, while the iconic Trefoil is embroidered at the thigh.', 'res/product/product3-1.jpg', 'res/product/product3-2.jpg', 'res/product/product3-3.jpg', 'res/product/product3-4.jpg'),
(015, 3, 'ADIDAS BECKENBAUER TRACK PANT', 95, 'bottom', 'black', 'large', 30, 'Paying homage to the former German footballer, this pair of track pants from adidas comes from the ‘Beckenbauer’ line-up. They’re styled in black with the signature stripes running along the seams, while the iconic Trefoil is embroidered at the thigh.', 'res/product/product3-1.jpg', 'res/product/product3-2.jpg', 'res/product/product3-3.jpg', 'res/product/product3-4.jpg'),
(016, 3, 'ADIDAS BECKENBAUER TRACK PANT', 95, 'bottom', 'white', 'small', 30, 'Paying homage to the former German footballer, this pair of track pants from adidas comes from the ‘Beckenbauer’ line-up. They’re styled in black with the signature stripes running along the seams, while the iconic Trefoil is embroidered at the thigh.', 'res/product/product3-1.jpg', 'res/product/product3-2.jpg', 'res/product/product3-3.jpg', 'res/product/product3-4.jpg'),
(017, 3, 'ADIDAS BECKENBAUER TRACK PANT', 95, 'bottom', 'white', 'medium', 30, 'Paying homage to the former German footballer, this pair of track pants from adidas comes from the ‘Beckenbauer’ line-up. They’re styled in black with the signature stripes running along the seams, while the iconic Trefoil is embroidered at the thigh.', 'res/product/product3-1.jpg', 'res/product/product3-2.jpg', 'res/product/product3-3.jpg', 'res/product/product3-4.jpg'),
(018, 3, 'ADIDAS BECKENBAUER TRACK PANT', 95, 'bottom', 'white', 'large', 30, 'Paying homage to the former German footballer, this pair of track pants from adidas comes from the ‘Beckenbauer’ line-up. They’re styled in black with the signature stripes running along the seams, while the iconic Trefoil is embroidered at the thigh.', 'res/product/product3-1.jpg', 'res/product/product3-2.jpg', 'res/product/product3-3.jpg', 'res/product/product3-4.jpg');

/*product 4*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(019, 4, 'ADIDAS YEEZY', 555, 'footwear', 'white', 'small', 30, 'The Adidas Yeezy Boost 350 V2 "Bone" takes the popular Yeezy model in a monochromatic direction. The shoe features a white-hued woven Primeknit upper. A tonal midsole wraps around Boost cushioning to create a cohesive version of the silhouette.', 'res/product/product4-1.jpg', 'res/product/product4-2.jpg', 'res/product/product4-3.jpg', 'res/product/product4-4.jpg'),
(020, 4, 'ADIDAS YEEZY', 555, 'footwear', 'white', 'medium', 30, 'The Adidas Yeezy Boost 350 V2 "Bone" takes the popular Yeezy model in a monochromatic direction. The shoe features a white-hued woven Primeknit upper. A tonal midsole wraps around Boost cushioning to create a cohesive version of the silhouette.', 'res/product/product4-1.jpg', 'res/product/product4-2.jpg', 'res/product/product4-3.jpg', 'res/product/product4-4.jpg'),
(021, 4, 'ADIDAS YEEZY', 555, 'footwear', 'white', 'large', 30, 'The Adidas Yeezy Boost 350 V2 "Bone" takes the popular Yeezy model in a monochromatic direction. The shoe features a white-hued woven Primeknit upper. A tonal midsole wraps around Boost cushioning to create a cohesive version of the silhouette.', 'res/product/product4-1.jpg', 'res/product/product4-2.jpg', 'res/product/product4-3.jpg', 'res/product/product4-4.jpg');

/*product 5*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(022, 5, 'NEW BALANCE ESSENTIALS CELEBRATE SPLIT LOGO TEE', 45, 'top', 'black', 'small', 30, 'This white tee from New Balance is a fresh addition to your sporty looks. Made from breathable cotton, it’s complete with retro branding in blue and orange on the chest - a nod to the brand’s long-standing heritage.', 'res/product/product5-1.jpg', 'res/product/product5-2.jpg', 'res/product/product5-3.jpg', 'res/product/product5-4.jpg'),
(023, 5, 'NEW BALANCE ESSENTIALS CELEBRATE SPLIT LOGO TEE', 45, 'top', 'black', 'medium', 30, 'This white tee from New Balance is a fresh addition to your sporty looks. Made from breathable cotton, it’s complete with retro branding in blue and orange on the chest - a nod to the brand’s long-standing heritage.', 'res/product/product5-1.jpg', 'res/product/product5-2.jpg', 'res/product/product5-3.jpg', 'res/product/product5-4.jpg'),
(024, 5, 'NEW BALANCE ESSENTIALS CELEBRATE SPLIT LOGO TEE', 45, 'top', 'black', 'large', 30, 'This white tee from New Balance is a fresh addition to your sporty looks. Made from breathable cotton, it’s complete with retro branding in blue and orange on the chest - a nod to the brand’s long-standing heritage.', 'res/product/product5-1.jpg', 'res/product/product5-2.jpg', 'res/product/product5-3.jpg', 'res/product/product5-4.jpg'),
(025, 5, 'NEW BALANCE ESSENTIALS CELEBRATE SPLIT LOGO TEE', 45, 'top', 'white', 'small', 30, 'This white tee from New Balance is a fresh addition to your sporty looks. Made from breathable cotton, it’s complete with retro branding in blue and orange on the chest - a nod to the brand’s long-standing heritage.', 'res/product/product5-1.jpg', 'res/product/product5-2.jpg', 'res/product/product5-3.jpg', 'res/product/product5-4.jpg'),
(026, 5, 'NEW BALANCE ESSENTIALS CELEBRATE SPLIT LOGO TEE', 45, 'top', 'white', 'medium', 30, 'This white tee from New Balance is a fresh addition to your sporty looks. Made from breathable cotton, it’s complete with retro branding in blue and orange on the chest - a nod to the brand’s long-standing heritage.', 'res/product/product5-1.jpg', 'res/product/product5-2.jpg', 'res/product/product5-3.jpg', 'res/product/product5-4.jpg'),
(027, 5, 'NEW BALANCE ESSENTIALS CELEBRATE SPLIT LOGO TEE', 45, 'top', 'white', 'large', 30, 'This white tee from New Balance is a fresh addition to your sporty looks. Made from breathable cotton, it’s complete with retro branding in blue and orange on the chest - a nod to the brand’s long-standing heritage.', 'res/product/product5-1.jpg', 'res/product/product5-2.jpg', 'res/product/product5-3.jpg', 'res/product/product5-4.jpg');

/*product 6*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(028, 6, 'NEW BALANCE ALL TERRAIN GRAPHIC', 50, 'top', 'black', 'small', 30, 'Upgrade your adventure gear with this white All Terrain tee from New Balance. Made from breathable cotton and cut to a relaxed fit, it’s complete with a blue Arctic Circle-inspired graphic on the back - and a woven brand patch at the chest, too.', 'res/product/product6-1.jpg', 'res/product/product6-2.jpg', 'res/product/product6-3.jpg', 'res/product/product6-4.jpg'),
(029, 6, 'NEW BALANCE ALL TERRAIN GRAPHIC', 50, 'top', 'black', 'medium', 30, 'Upgrade your adventure gear with this white All Terrain tee from New Balance. Made from breathable cotton and cut to a relaxed fit, it’s complete with a blue Arctic Circle-inspired graphic on the back - and a woven brand patch at the chest, too.', 'res/product/product6-1.jpg', 'res/product/product6-2.jpg', 'res/product/product6-3.jpg', 'res/product/product6-4.jpg'),
(030, 6, 'NEW BALANCE ALL TERRAIN GRAPHIC', 50, 'top', 'black', 'large', 30, 'Upgrade your adventure gear with this white All Terrain tee from New Balance. Made from breathable cotton and cut to a relaxed fit, it’s complete with a blue Arctic Circle-inspired graphic on the back - and a woven brand patch at the chest, too.', 'res/product/product6-1.jpg', 'res/product/product6-2.jpg', 'res/product/product6-3.jpg', 'res/product/product6-4.jpg'),
(031, 6, 'NEW BALANCE ALL TERRAIN GRAPHIC', 50, 'top', 'white', 'small', 30, 'Upgrade your adventure gear with this white All Terrain tee from New Balance. Made from breathable cotton and cut to a relaxed fit, it’s complete with a blue Arctic Circle-inspired graphic on the back - and a woven brand patch at the chest, too.', 'res/product/product6-1.jpg', 'res/product/product6-2.jpg', 'res/product/product6-3.jpg', 'res/product/product6-4.jpg'),
(032, 6, 'NEW BALANCE ALL TERRAIN GRAPHIC', 50, 'top', 'white', 'medium', 30, 'Upgrade your adventure gear with this white All Terrain tee from New Balance. Made from breathable cotton and cut to a relaxed fit, it’s complete with a blue Arctic Circle-inspired graphic on the back - and a woven brand patch at the chest, too.', 'res/product/product6-1.jpg', 'res/product/product6-2.jpg', 'res/product/product6-3.jpg', 'res/product/product6-4.jpg'),
(033, 6, 'NEW BALANCE ALL TERRAIN GRAPHIC', 50, 'top', 'white', 'large', 30, 'Upgrade your adventure gear with this white All Terrain tee from New Balance. Made from breathable cotton and cut to a relaxed fit, it’s complete with a blue Arctic Circle-inspired graphic on the back - and a woven brand patch at the chest, too.', 'res/product/product6-1.jpg', 'res/product/product6-2.jpg', 'res/product/product6-3.jpg', 'res/product/product6-4.jpg');

/*product 7*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(034, 7, 'NEW BALANCE ATHLETICS NATURE STATE SHORT', 75, 'bottoms', 'black', 'small', 30, 'Whether you’re hitting the gym or lounging at home, reach for these blue shorts from New Balance. Crafted from pure cotton, they’re cut to a relaxed fit with an elasticated drawstring waist for a comfortable fit. To finish, they feature two side pockets for your essentials and are signed off at the leg with tonal branding.', 'res/product/product7-1.jpg', 'res/product/product7-2.jpg', 'res/product/product7-3.jpg', 'res/product/product7-4.jpg'),
(035, 7, 'NEW BALANCE ATHLETICS NATURE STATE SHORT', 75, 'bottoms', 'black', 'medium', 30, 'Whether you’re hitting the gym or lounging at home, reach for these blue shorts from New Balance. Crafted from pure cotton, they’re cut to a relaxed fit with an elasticated drawstring waist for a comfortable fit. To finish, they feature two side pockets for your essentials and are signed off at the leg with tonal branding.', 'res/product/product7-1.jpg', 'res/product/product7-2.jpg', 'res/product/product7-3.jpg', 'res/product/product7-4.jpg'),
(036, 7, 'NEW BALANCE ATHLETICS NATURE STATE SHORT', 75, 'bottoms', 'black', 'large', 30, 'Whether you’re hitting the gym or lounging at home, reach for these blue shorts from New Balance. Crafted from pure cotton, they’re cut to a relaxed fit with an elasticated drawstring waist for a comfortable fit. To finish, they feature two side pockets for your essentials and are signed off at the leg with tonal branding.', 'res/product/product7-1.jpg', 'res/product/product7-2.jpg', 'res/product/product7-3.jpg', 'res/product/product7-4.jpg'),
(037, 7, 'NEW BALANCE ATHLETICS NATURE STATE SHORT', 75, 'bottoms', 'blue', 'small', 30, 'Whether you’re hitting the gym or lounging at home, reach for these blue shorts from New Balance. Crafted from pure cotton, they’re cut to a relaxed fit with an elasticated drawstring waist for a comfortable fit. To finish, they feature two side pockets for your essentials and are signed off at the leg with tonal branding.', 'res/product/product7-1.jpg', 'res/product/product7-2.jpg', 'res/product/product7-3.jpg', 'res/product/product7-4.jpg'),
(038, 7, 'NEW BALANCE ATHLETICS NATURE STATE SHORT', 75, 'bottoms', 'blue', 'medium', 30, 'Whether you’re hitting the gym or lounging at home, reach for these blue shorts from New Balance. Crafted from pure cotton, they’re cut to a relaxed fit with an elasticated drawstring waist for a comfortable fit. To finish, they feature two side pockets for your essentials and are signed off at the leg with tonal branding.', 'res/product/product7-1.jpg', 'res/product/product7-2.jpg', 'res/product/product7-3.jpg', 'res/product/product7-4.jpg'),
(039, 7, 'NEW BALANCE ATHLETICS NATURE STATE SHORT', 75, 'bottoms', 'blue', 'large', 30, 'Whether you’re hitting the gym or lounging at home, reach for these blue shorts from New Balance. Crafted from pure cotton, they’re cut to a relaxed fit with an elasticated drawstring waist for a comfortable fit. To finish, they feature two side pockets for your essentials and are signed off at the leg with tonal branding.', 'res/product/product7-1.jpg', 'res/product/product7-2.jpg', 'res/product/product7-3.jpg', 'res/product/product7-4.jpg');

/*product 8*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(040, 8, 'NEW BALANCE BB550NCB', 179, 'footwear', 'white', 'small', 30, 'New Balance champions ‘80s style with its basketball and streetwear inspired 550 silhouette. Revived in recent years by supermodels and celebrities, alike, the stylish pair are kept clean in monochromatic colours.', 'res/product/product8-1.jpg', 'res/product/product8-2.jpg', 'res/product/product8-3.jpg', 'res/product/product8-4.jpg'),
(041, 8, 'NEW BALANCE BB550NCB', 179, 'footwear', 'white', 'medium', 30, 'New Balance champions ‘80s style with its basketball and streetwear inspired 550 silhouette. Revived in recent years by supermodels and celebrities, alike, the stylish pair are kept clean in monochromatic colours.', 'res/product/product8-1.jpg', 'res/product/product8-2.jpg', 'res/product/product8-3.jpg', 'res/product/product8-4.jpg'),
(042, 8, 'NEW BALANCE BB550NCB', 179, 'footwear', 'white', 'large', 30, 'New Balance champions ‘80s style with its basketball and streetwear inspired 550 silhouette. Revived in recent years by supermodels and celebrities, alike, the stylish pair are kept clean in monochromatic colours.', 'res/product/product8-1.jpg', 'res/product/product8-2.jpg', 'res/product/product8-3.jpg', 'res/product/product8-4.jpg');

/*product 9*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(043, 9, 'NIKE FANTASY TEE', 45, 'top', 'black', 'small', 30, 'Nike opts for a whimsical approach to styling with this black tee. Crafted from lightweight cotton, its cut to a relaxed fit, then decorated with a natural take on the brand’s Futura logo – which features woodland mulch, wild mushrooms and a pair of dunks – at the chest.', 'res/product/product9-1.jpg', 'res/product/product9-2.jpg', 'res/product/product9-3.jpg', 'res/product/product9-4.jpg'),
(044, 9, 'NIKE FANTASY TEE', 45, 'top', 'black', 'medium', 30, 'Nike opts for a whimsical approach to styling with this black tee. Crafted from lightweight cotton, its cut to a relaxed fit, then decorated with a natural take on the brand’s Futura logo – which features woodland mulch, wild mushrooms and a pair of dunks – at the chest.', 'res/product/product9-1.jpg', 'res/product/product9-2.jpg', 'res/product/product9-3.jpg', 'res/product/product9-4.jpg'),
(045, 9, 'NIKE FANTASY TEE', 45, 'top', 'black', 'large', 30, 'Nike opts for a whimsical approach to styling with this black tee. Crafted from lightweight cotton, its cut to a relaxed fit, then decorated with a natural take on the brand’s Futura logo – which features woodland mulch, wild mushrooms and a pair of dunks – at the chest.', 'res/product/product9-1.jpg', 'res/product/product9-2.jpg', 'res/product/product9-3.jpg', 'res/product/product9-4.jpg'),
(046, 9, 'NIKE FANTASY TEE', 45, 'top', 'white', 'small', 30, 'Nike opts for a whimsical approach to styling with this black tee. Crafted from lightweight cotton, its cut to a relaxed fit, then decorated with a natural take on the brand’s Futura logo – which features woodland mulch, wild mushrooms and a pair of dunks – at the chest.', 'res/product/product9-1.jpg', 'res/product/product9-2.jpg', 'res/product/product9-3.jpg', 'res/product/product9-4.jpg'),
(047, 9, 'NIKE FANTASY TEE', 45, 'top', 'white', 'medium', 30, 'Nike opts for a whimsical approach to styling with this black tee. Crafted from lightweight cotton, its cut to a relaxed fit, then decorated with a natural take on the brand’s Futura logo – which features woodland mulch, wild mushrooms and a pair of dunks – at the chest.', 'res/product/product9-1.jpg', 'res/product/product9-2.jpg', 'res/product/product9-3.jpg', 'res/product/product9-4.jpg'),
(048, 9, 'NIKE FANTASY TEE', 45, 'top', 'white', 'large', 30, 'Nike opts for a whimsical approach to styling with this black tee. Crafted from lightweight cotton, its cut to a relaxed fit, then decorated with a natural take on the brand’s Futura logo – which features woodland mulch, wild mushrooms and a pair of dunks – at the chest.', 'res/product/product9-1.jpg', 'res/product/product9-2.jpg', 'res/product/product9-3.jpg', 'res/product/product9-4.jpg');

/*product 10*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(049, 10, 'NIKE MAGIC GRAPHIC TEE', 59, 'top', 'black', 'small', 30, 'Nike elevates your tee collection with this bold grey graphic tee. It’s made from soft cotton, features a classic crewneck and is enhanced with trippy artwork at the chest.', 'res/product/product10-1.jpg', 'res/product/product10-2.jpg', 'res/product/product10-3.jpg', 'res/product/product10-4.jpg'),
(050, 10, 'NIKE MAGIC GRAPHIC TEE', 59, 'top', 'black', 'medium', 30, 'Nike elevates your tee collection with this bold grey graphic tee. It’s made from soft cotton, features a classic crewneck and is enhanced with trippy artwork at the chest.', 'res/product/product10-1.jpg', 'res/product/product10-2.jpg', 'res/product/product10-3.jpg', 'res/product/product10-4.jpg'),
(051, 10, 'NIKE MAGIC GRAPHIC TEE', 59, 'top', 'black', 'large', 30, 'Nike elevates your tee collection with this bold grey graphic tee. It’s made from soft cotton, features a classic crewneck and is enhanced with trippy artwork at the chest.', 'res/product/product10-1.jpg', 'res/product/product10-2.jpg', 'res/product/product10-3.jpg', 'res/product/product10-4.jpg'),
(052, 10, 'NIKE MAGIC GRAPHIC TEE', 59, 'top', 'white', 'small', 30, 'Nike elevates your tee collection with this bold grey graphic tee. It’s made from soft cotton, features a classic crewneck and is enhanced with trippy artwork at the chest.', 'res/product/product10-1.jpg', 'res/product/product10-2.jpg', 'res/product/product10-3.jpg', 'res/product/product10-4.jpg'),
(053, 10, 'NIKE MAGIC GRAPHIC TEE', 59, 'top', 'white', 'medium', 30, 'Nike elevates your tee collection with this bold grey graphic tee. It’s made from soft cotton, features a classic crewneck and is enhanced with trippy artwork at the chest.', 'res/product/product10-1.jpg', 'res/product/product10-2.jpg', 'res/product/product10-3.jpg', 'res/product/product10-4.jpg'),
(054, 10, 'NIKE MAGIC GRAPHIC TEE', 59, 'top', 'white', 'large', 30, 'Nike elevates your tee collection with this bold grey graphic tee. It’s made from soft cotton, features a classic crewneck and is enhanced with trippy artwork at the chest.', 'res/product/product10-1.jpg', 'res/product/product10-2.jpg', 'res/product/product10-3.jpg', 'res/product/product10-4.jpg');

/*product 11*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(055, 11, 'NIKE NSW COMMUTER PANT', 115, 'bottom', 'black', 'small', 30, 'Nike fuses its usual sporty aesthetic with a street-ready vibe to craft these commuter pants. Built to take you from the courts to the streets, they’re made from lightweight polyester, styled in black and cut to a relaxed fit, complete with the brand’s Swoosh logo sitting proudly on one thigh.', 'res/product/product11-1.jpg', 'res/product/product11-2.jpg', 'res/product/product11-3.jpg', 'res/product/product11-4.jpg'),
(056, 11, 'NIKE NSW COMMUTER PANT', 115, 'bottom', 'black', 'medium', 30, 'Nike fuses its usual sporty aesthetic with a street-ready vibe to craft these commuter pants. Built to take you from the courts to the streets, they’re made from lightweight polyester, styled in black and cut to a relaxed fit, complete with the brand’s Swoosh logo sitting proudly on one thigh.', 'res/product/product11-1.jpg', 'res/product/product11-2.jpg', 'res/product/product11-3.jpg', 'res/product/product11-4.jpg'),
(057, 11, 'NIKE NSW COMMUTER PANT', 115, 'bottom', 'black', 'large', 30, 'Nike fuses its usual sporty aesthetic with a street-ready vibe to craft these commuter pants. Built to take you from the courts to the streets, they’re made from lightweight polyester, styled in black and cut to a relaxed fit, complete with the brand’s Swoosh logo sitting proudly on one thigh.', 'res/product/product11-1.jpg', 'res/product/product11-2.jpg', 'res/product/product11-3.jpg', 'res/product/product11-4.jpg'),
(058, 11, 'NIKE NSW COMMUTER PANT', 115, 'bottom', 'white', 'small', 30, 'Nike fuses its usual sporty aesthetic with a street-ready vibe to craft these commuter pants. Built to take you from the courts to the streets, they’re made from lightweight polyester, styled in black and cut to a relaxed fit, complete with the brand’s Swoosh logo sitting proudly on one thigh.', 'res/product/product11-1.jpg', 'res/product/product11-2.jpg', 'res/product/product11-3.jpg', 'res/product/product11-4.jpg'),
(059, 11, 'NIKE NSW COMMUTER PANT', 115, 'bottom', 'white', 'medium', 30, 'Nike fuses its usual sporty aesthetic with a street-ready vibe to craft these commuter pants. Built to take you from the courts to the streets, they’re made from lightweight polyester, styled in black and cut to a relaxed fit, complete with the brand’s Swoosh logo sitting proudly on one thigh.', 'res/product/product11-1.jpg', 'res/product/product11-2.jpg', 'res/product/product11-3.jpg', 'res/product/product11-4.jpg'),
(060, 11, 'NIKE NSW COMMUTER PANT', 115, 'bottom', 'white', 'large', 30, 'Nike fuses its usual sporty aesthetic with a street-ready vibe to craft these commuter pants. Built to take you from the courts to the streets, they’re made from lightweight polyester, styled in black and cut to a relaxed fit, complete with the brand’s Swoosh logo sitting proudly on one thigh.', 'res/product/product11-1.jpg', 'res/product/product11-2.jpg', 'res/product/product11-3.jpg', 'res/product/product11-4.jpg');

/*product 12*/
INSERT INTO `Product` ( productindex, productId, name, price, category, color, size, stock, description, image1, image2, image3, image4) VALUES 
(061, 12, 'NIKE AIR FORCE 1 ''07 LV8', 189, 'footwear', 'white', 'small', 30, 'Nike celebrates its 40th anniversary of the iconic Air Force 1 with this off-white and green rendition. Featuring all the classic details, they’re formed with tumbled leather uppers with a striking green Swoosh at the sidewalls - with the same shade at the heel that\'s detailed with contrasting white ‘Nike Air’ branding. Other highlights include a debossed ‘40’ at the heel - in honour of its 1982 release date - and subtle gold accents to finish off this celebratory silhouette.', 'res/product/product12-1.jpg', 'res/product/product12-2.jpg', 'res/product/product12-3.jpg', 'res/product/product12-4.jpg'),
(062, 12, 'NIKE AIR FORCE 1 ''07 LV8', 189, 'footwear', 'white', 'medium', 30, 'Nike celebrates its 40th anniversary of the iconic Air Force 1 with this off-white and green rendition. Featuring all the classic details, they’re formed with tumbled leather uppers with a striking green Swoosh at the sidewalls - with the same shade at the heel that\'s detailed with contrasting white ‘Nike Air’ branding. Other highlights include a debossed ‘40’ at the heel - in honour of its 1982 release date - and subtle gold accents to finish off this celebratory silhouette.', 'res/product/product12-1.jpg', 'res/product/product12-2.jpg', 'res/product/product12-3.jpg', 'res/product/product12-4.jpg'),
(063, 12, 'NIKE AIR FORCE 1 ''07 LV8', 189, 'footwear', 'white', 'large', 30, 'Nike celebrates its 40th anniversary of the iconic Air Force 1 with this off-white and green rendition. Featuring all the classic details, they’re formed with tumbled leather uppers with a striking green Swoosh at the sidewalls - with the same shade at the heel that\'s detailed with contrasting white ‘Nike Air’ branding. Other highlights include a debossed ‘40’ at the heel - in honour of its 1982 release date - and subtle gold accents to finish off this celebratory silhouette.', 'res/product/product12-1.jpg', 'res/product/product12-2.jpg', 'res/product/product12-3.jpg', 'res/product/product12-4.jpg');